terraform_role_arn         = "arn:aws:iam::307487914182:role/K24.Terraform"
source_repo_branch         = "develop"
db_instance_class          = "db.t3.medium"
domain_name                = "stage.kfzteile24.io"
environment                = "stage"
stage                      = "staging-1"
ecp_new_order_sns          = "arn:aws:sns:eu-central-1:433833759926:production-order-export"