#
# Profile documentation: https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-profiles
#
spring:
  profiles.active: development,default

---
spring:
  profiles: development

  datasource:
    jdbcUrl: ${JDBC_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PW}
    poolName: sales-order-hub
