#
# Profile documentation: https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-profiles
#
spring:
  # Per default the application starts with the default,local profile. This is good for local development.
  # You can override this with the
  # a)  commandline option
  #      java -jar application.jar -Dspring.profiles.active=default,local or default,production
  #  b) via environment variable
  #      export SPRING_PROFILES_ACTIVE=default,local or default,production
  #      java -jar application.jar
  profiles.active: default,local

#
# Camunda BPM configuration
#   The Camuinda settings do not work with profiles. Keep it here (and use dynamic values to overwrite defaults instead)
#
camunda:
  bpm:
    database:
      # IMPORTANT! flyway is responsible for database changes
      schema-update: false
      schema-name: bpm
      table-prefix: ${camunda.bpm.database.schema-name}.
    admin-user:
      id: ${soh_camunda_username:demo}
      password: ${soh_camunda_password:demo}
      firstName: K24Admin 
    filter:
      create: All tasks
    history-level: FULL
    history-level-default: FULL
kfzteile:
  #
  # Delete processes that are not used?
  # KEEP OFF ON PRODUCTION
  #
  deleteUnusedProcesses: true
