

---
spring:
  profiles: default

  # overwrite env specific settings in  the corresponding application-${env}.yml
  datasource:
    jdbcUrl: jdbc:postgresql://${soh_db_host}:${soh_db_port}/${soh_db_database}?currentSchema=public
    username: ${soh_db_username}
    password: ${soh_db_password}
    poolName: sales-order-hub
    data-source-properties:
      stringtype: unspecified

  jpa:
    open-in-view: false

  management:
    endpoints:
      web:
        exposure:
          include: info, health,configprops

