#
# Camunda BPM configuration
#
camunda:
  bpm:
    database:
      # IMPORTANT! flyway is responsible for database changes
      schema-update: false
      schema-name: bpm
      table-prefix: ${camunda.bpm.database.schema-name}.
    admin-user:
      id: demo
      password: demo
      firstName: Demo
    filter:
      create: All tasks
    history-level: FULL
    history-level-default: FULL
kfzteile:
  #
  # Delete processes that are not used?
  # KEEP OFF ON PRODUCTION
  #
  deleteUnusedProcesses: true
