#
# This profile is used by the github actions to run the unit & integration tests
#
---
spring:
  profiles: test

  flyway:
    baselineOnMigrate: true
    locations: classpath:/db/migration

  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: validate
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5432/soh?currentSchema=public
    username: soh
    password: soh
  main:
    allow-bean-definition-overriding: true

  #AWS
soh:
  sns:
    topic:
      orderCreatedV2:         arn:aws:sns:eu-central-1:000000000000:soh-order-created-v2
      orderCompleted:         arn:aws:sns:eu-central-1:000000000000:soh-sales-order-completed-v1
      invoiceAddressChanged:  arn:aws:sns:eu-central-1:000000000000:soh-invoice-address-changed
      salesOrderRowCancelled: arn:aws:sns:eu-central-1:000000000000:soh-sales-order-row-cancelled
      salesOrderCancelled:    arn:aws:sns:eu-central-1:000000000000:soh-sales-order-cancelled
      orderInvoiceCreatedV1:  arn:aws:sns:eu-central-1:000000000000:soh-order-invoice-created-v1
      shipmentConfirmedV1:    arn:aws:sns:eu-central-1:000000000000:soh-shipment-confirmed-v1
      returnOrderCreatedV1:   arn:aws:sns:eu-central-1:000000000000:soh-return-order-created-v1
      coreInvoiceReceivedV1:  arn:aws:sns:eu-central-1:000000000000:soh-core-invoice-received-v1
      creditNoteCreatedV1:    arn:aws:sns:eu-central-1:000000000000:soh-credit-note-created-v1
      creditNoteReceivedV1:   arn:aws:sns:eu-central-1:000000000000:soh-credit-note-received-v1
      creditNoteDocumentGeneratedV1: arn:aws:sns:eu-central-1:000000000000:soh-credit-note-document-generated-v1
      migrationOrderCreatedV2: arn:aws:sns:eu-central-1:000000000000:migration-soh-order-created-v2
      migrationSalesOrderRowCancelledV1: arn:aws:sns:eu-central-1:000000000000:migration-soh-sales-order-row-cancelled-v1
      migrationSalesOrderCancelledV1: arn:aws:sns:eu-central-1:000000000000:migration-soh-sales-order-cancelled-v1
      migrationReturnOrderCreatedV1: arn:aws:sns:eu-central-1:000000000000:migration-soh-return-order-created-v1
      dropshipmentOrderCreatedV1: arn:aws:sns:eu-central-1:000000000000:soh-dropshipment-order-created-v1
      dropshipmentOrderReturnNotifiedV1: arn:aws:sns:eu-central-1:000000000000:soh-dropshipment-order-return-notified-v1
      payoutReceiptConfirmationReceivedV1: arn:aws:sns:eu-central-1:000000000000:soh-payout-receipt-confirmation-received-v1
      invoicePdfGenerationTriggeredV1: arn:aws:sns:eu-central-1:000000000000:soh-invoice-pdf-generation-triggered-v1
  sqs:
    queue:
      ecpShopOrders:                  http://localhost:4566/000000000000/soh-ecp-shop-orders-queue
      bcShopOrders:                   http://localhost:4566/000000000000/soh-bc-shop-orders-queue
      coreShopOrders:                 http://localhost:4566/000000000000/soh-core-shop-orders-queue
      invoicesFromCore:               http://localhost:4566/000000000000/soh-invoices-from-core-queue
      d365OrderPaymentSecured:        http://localhost:4566/000000000000/soh-d365-order-payment-secured-queue
      dropshipmentShipmentConfirmed:  http://localhost:4566/000000000000/soh-dropshipment-shipment-confirmed-queue
      dropshipmentPurchaseOrderBooked: http://localhost:4566/000000000000/soh-dropshipment-purchase-order-booked-queue
      dropshipmentPurchaseOrderReturnNotified: http://localhost:4566/000000000000/soh-dropshipment-purchase-order-return-notified-queue
      dropshipmentPurchaseOrderReturnConfirmed: http://localhost:4566/000000000000/soh-dropshipment-purchase-order-return-confirmed-queue
      coreSalesCreditNoteCreated:     http://localhost:4566/000000000000/soh-core-sales-credit-note-created-queue
      coreSalesInvoiceCreated:        http://localhost:4566/000000000000/soh-core-sales-invoice-created-queue
      migrationCoreSalesOrderCreated: http://localhost:4566/000000000000/migration-core-sales-order-created-queue
      migrationCoreSalesInvoiceCreated: http://localhost:4566/000000000000/migration-core-sales-invoice-created-queue
      migrationCoreSalesCreditNoteCreated: http://localhost:4566/000000000000/migration-core-sales-credit-note-created-queue
      parcelShipped:                  http://localhost:4566/000000000000/soh-parcel-shipped-queue
      paypalRefundInstructionSuccessful: http://localhost:4566/000000000000/soh-paypal-refund-instruction-successful-queue
      coreSalesOrderCancelled:        http://localhost:4566/000000000000/soh-core-sales-order-cancelled-queue
  aws:
    config:
      maxNumberOfMessages: 10
      waitTimeOut: 10
  http:
    connection:
      timeout: 20

cloud:
  aws:
    endpoint:
      url: http://localhost:4566
    region:
      static: eu-central-1
    stack:
      auto: false
    credentials:
      access-key: "000000000000"
      secret-key: "000000000000"

camunda:
  bpm:
    database:
      schema-update: true
      schema-name: bpm
    admin-user:
      id: ${soh_camunda_username:demo}
      password: ${soh_camunda_password:demo}
      firstName: K24Admin
    filter:
      create: All tasks
    history-level: ACTIVITY

infrastructureEnvironment: stage

kfzteile:
  pricing-service:
    url: https://s8vlbhblll.execute-api.eu-central-1.amazonaws.com/stage
    apiKey:  ${pricing_service_api_key:api_key}
  product-data-hub:
    pdhUrl: http://localhost:18080
    authUrl: http://localhost:18080/oauth2/token
  process-config:
    sales-order-process:
      dropshipment-order-booked-timer: R/PT10S
      dropshipment-shipment-confirmed-timer: R/PT10S
  dropshipment:
    splitgenarts:
      ecp:
        - 10033
        - 10034
        - 10035
      deshop:
        - 10040
        - 10041
        - 10042
  persistent-properties:
    - key: pauseDropshipmentProcessing
      value: false
      overwrite-on-startup: false
    - key: preventDropshipmentOrderReturnConfirmed
      value: true
      overwrite-on-startup: true
  email:
    source: ${soh_source_email:fake.email@kfzteile24.de}
    destination: ${finance_destination_email:${kfzteile.email.source}}
    cc: ${refund_cc_email:${kfzteile.email.source}}
    password: password

ignoreCoreSalesInvoice: false
ignoreCoreCreditNote: false
ignoreMigrationCoreSalesInvoice: false
ignoreMigrationCoreSalesCreditNote: false
ignoreMigrationCoreSalesOrder: false
ignoreSalesOrderSplitter: false
ignoreSetDissolvement: false
preventSetProcessing: false
