#
# Profile documentation: https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-profiles
#
spring:
  profiles.active: development,default

---
spring:
  profiles: development

  datasource:
    jdbcUrl: jdbc:postgresql://${soh_db_host}:${soh_db_port}/${soh_db_database}?currentSchema=public
    username: ${soh_db_username}
    password: ${soh_db_password}
    poolName: sales-order-hub

cloud:
  aws:
    region:
      static: eu-central-1
    stack:
      auto: false
    credentials:
      access-key: ${aws_accessKey}
      secret-key: ${aws_sercretKey}

#AWS
soh:
  sns:
    topic:
      orderCreated: ${soh_order_created}
