#
# Profile documentation: https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-profiles
#

logging:
  level:
    com.zaxxer.hikari: DEBUG

spring:
  datasource:
    jdbcUrl: jdbc:postgresql://${soh_db_host}:${soh_db_port}/${soh_db_database}?currentSchema=public
    username: ${soh_db_username}
    password: ${soh_db_password}
    data-source-properties:
      stringtype: unspecified
    pool-name: sales-order-hub
    maximum-pool-size: 150
    # 48 connections for SqsListener (8 queues * (5 messages_per_batch + 1) + 5 spare connections for e.g. manual access
    # (s. https://github.com/awspring/spring-cloud-aws/blob/c63f77ff5fe9fa5d8e23ae11c4cbc19ecd99ab15/spring-cloud-aws-messaging/src/main/java/io/awspring/cloud/messaging/listener/SimpleMessageListenerContainer.java#L203)
    minimum-idle: 25

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true

  management:
    endpoints:
      web:
        exposure:
          include: info, health,configprops
#  Override the path for camunda rest engine if needed.
#  jersey:
#    application-path:

cloud:
  aws:
    region:
      static: eu-central-1
    stack:
      auto: false


#AWS
soh:
  sns:
    topic:
      orderCreatedV2: ${soh_order_created_v2}
      orderCompleted: ${soh_order_completed}
      orderCancelled: ${soh_order_cancelled}
      orderItemCancelled: ${soh_order_item_cancelled}
      orderRowsCancelled: ${soh_order_rows_cancelled}
      invoiceAddressChanged: ${soh_invoice_address_changed}
      deliveryAddressChanged: ${soh_delivery_address_changed}
      salesOrderRowCancelled: ${soh_sales_order_row_cancellation}
      salesOrderCancelled: ${soh_sales_order_cancellation}
      orderInvoiceCreatedV1: ${soh_order_invoice_created_v1}
      shipmentConfirmedV1: ${sns_soh_shipment_confirmed_v1}
  sqs:
    queue:
      ecpShopOrders: ${soh_sqs_ecp_shop_orders}
      bcShopOrders: ${soh_sqs_bc_shop_orders}
      coreShopOrders: ${soh_sqs_core_shop_orders}
      orderItemShipped: ${soh_sqs_order_item_shipped}
      orderPaymentSecured: ${soh_sqs_order_payment_secured}
      orderItemTransmittedToLogistic: ${soh_sqs_order_item_transmitted_to_logistic}
      orderItemPackingStarted: ${soh_sqs_order_item_packing_started}
      orderItemTrackingIdReceived: ${soh_sqs_order_item_tracking_id_received}
      orderItemTourStarted: ${soh_sqs_order_item_tour_started}
      invoicesFromCore: ${soh_sqs_invoices_from_core}
      coreCancellation: ${soh_sqs_core_cancellation}
      subsequentDeliveryReceived: ${soh_sqs_subsequent_delivery_received}
      d365OrderPaymentSecured: ${soh_sqs_d365_order_payment_secured}
      dropshipmentShipmentConfirmed: ${soh_sqs_dropshipment_shipment_confirmed}
  aws:
    config:
      maxNumberOfMessages: 10
      waitTimeOut: 10


#
# Camunda BPM configuration
#   The Camunda settings do not work with profiles. Keep it here (and use dynamic values to overwrite defaults instead)
#
camunda:
  bpm:
    database:
      # IMPORTANT! flyway is responsible for database changes
      schema-update: false
      schema-name: bpm
      table-prefix: ${camunda.bpm.database.schema-name}.
    admin-user:
      id: ${soh_camunda_username:demo}
      password: ${soh_camunda_password:demo}
      firstName: K24Admin
    filter:
      create: All tasks
    history-level: FULL
    history-level-default: FULL

# swagger endpoint documentation
springdoc:
  swagger-ui:
    path: /api/swagger
  api-docs:
    path: /api-docs

swagger:
  api:
    title: Sales Order Hub - API Doc
    description: API documentation of Sales Order Hub for direct requests
    version: 1.0
    controller:
      basepackage: de.kfzteile24.salesOrderHub

kfzteile:
  #
  # Delete processes that are not used?
  # KEEP OFF ON PRODUCTION
  #
  deleteUnusedProcesses: true
