#
# Profile documentation: https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-profiles
#
spring:
  datasource:
    jdbcUrl: jdbc:postgresql://${soh_db_host}:${soh_db_port}/${soh_db_database}?currentSchema=public
    username: ${soh_db_username}
    password: ${soh_db_password}
    poolName: sales-order-hub
    data-source-properties:
      stringtype: unspecified

  jpa:
    open-in-view: false

  management:
    endpoints:
      web:
        exposure:
          include: info, health,configprops

cloud:
  aws:
    region:
      static: eu-central-1
    stack:
      auto: false

#AWS
soh:
  sns:
    topic:
      orderCreated: ${soh_order_created}
      orderCompleted: ${soh_order_completed}
      orderCancelled: ${soh_order_cancelled}
      orderItemCancelled: ${soh_order_item_cancelled}
      invoiceAddressChanged: ${soh_invoice_address_changed}
      deliveryAddressChanged: ${soh_delivery_address_changed}
  sqs:
    maxMessageRetrieves: 5
    queue:
      ecpShopOrders: ${soh_sqs_ecp_shop_orders}
      orderItemShipped: ${soh_sqs_order_item_shipped}
      orderPaymentSecured: ${soh_sqs_order_payment_secured}
      orderItemTransmittedToLogistic: ${soh_sqs_order_item_transmitted_to_logistic}
      orderItemPackingStarted: ${soh_sqs_order_item_packing_started}
      orderItemTrackingIdReceived: ${soh_sqs_order_item_tracking_id_received}
      orderItemTourStarted: ${soh_sqs_order_item_tour_started}
      invoicesFromCore: ${soh_sqs_invoices_from_core}

#
# Camunda BPM configuration
#   The Camunda settings do not work with profiles. Keep it here (and use dynamic values to overwrite defaults instead)
#
camunda:
  bpm:
    database:
      # IMPORTANT! flyway is responsible for database changes
      schema-update: false
      schema-name: bpm
      table-prefix: ${camunda.bpm.database.schema-name}.
    admin-user:
      id: ${soh_camunda_username:demo}
      password: ${soh_camunda_password:demo}
      firstName: K24Admin 
    filter:
      create: All tasks
    history-level: FULL
    history-level-default: FULL

# swagger endpoint documentation
springdoc:
  swagger-ui:
    path: /api/swagger
  api-docs:
    path: /api-docs

swagger:
  api:
    title: Sales Order Hub - API Doc
    description: API documentation of Sales Order Hub for direct requests
    version: 1.0
    controller:
      basepackage: de.kfzteile24.salesOrderHub

kfzteile:
  #
  # Delete processes that are not used?
  # KEEP OFF ON PRODUCTION
  #
  deleteUnusedProcesses: true
