#
# Profile documentation: https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-profiles
#
spring:
  profiles.active: development,default

---
spring:
  profiles: development

  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5432/soh?currentSchema=public
    username: postgres
    password: postgres
    poolName: sales-order-hub
