pdh_client_id: ENC[AES256_GCM,data:/xL9DvAmZmQiiaAASeUryfgaFMJS1ZUQ5I0=,iv:VDLVR1T3ckLaRlefXZbVrjT8+aBlOkif8pdmc++k6NY=,tag:uzqTROKrT3dvGkH7LtnRXQ==,type:str]
pdh_client_secret: ENC[AES256_GCM,data:tqRNyNYRLnqn7jqD1V8QkntnrhoYup52XCaUPVXe5T5yAi5S6z8euHrVIIevCCfiCHqi,iv:q2+Olc2mCUfwyuCl2QfhQSI47suLuBxvEpzCmW2xR7I=,tag:bC4TDq1dlafz+4suAiQSKQ==,type:str]
sops:
    kms:
    -   arn: arn:aws:kms:eu-central-1:823844813531:key/59f4e215-67f4-48bc-9d03-da65870b80e7
        role: arn:aws:iam::823844813531:role/K24.AccessSopsKMS
        created_at: '2022-05-17T06:24:58Z'
        enc: AQICAHhlE+W1VDoEfCyLFJNKxgsoTZvknpSGWiMaH4zFK6yb+AGh42iimP034euei11U4B6mAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMNPzzEbXs8tGHhyCIAgEQgDsXvoooFNGp0yV03ROKA0U+UjFRZKZfesvQA/Dn8QPR7MmclRtfqgszU9kd1s0Z3hyll03VmyVWwmDn7g==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    lastmodified: '2022-05-17T06:32:16Z'
    mac: ENC[AES256_GCM,data:cvEa8OQdX4ZAOqLWiuTqhETtU8Qk12fXw5qL27cQatYFVGUrbYGgyuebTkGyycA16yKxYcofd7s61bifUfgKK/zwEjqIdKJfOctEZDom9kdbU+u9Y0OeerW5GruiqJb0cY8SEYUZl9yc7xQapc+oivDu46YnDsDihlpXeknPFTE=,iv:CnESnkryCxgUZeUkHk51LXgi0UCwC1WPlfJCsY7F5F4=,tag:4nKQia7xLd2z5wiLMR357w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.4.0
