pdh_client_id: ENC[AES256_GCM,data:/xL9DvAmZmQiiaAASeUryfgaFMJS1ZUQ5I0=,iv:VDLVR1T3ckLaRlefXZbVrjT8+aBlOkif8pdmc++k6NY=,tag:uzqTROKrT3dvGkH7LtnRXQ==,type:str]
pdh_client_secret: ENC[AES256_GCM,data:tqRNyNYRLnqn7jqD1V8QkntnrhoYup52XCaUPVXe5T5yAi5S6z8euHrVIIevCCfiCHqi,iv:q2+Olc2mCUfwyuCl2QfhQSI47suLuBxvEpzCmW2xR7I=,tag:bC4TDq1dlafz+4suAiQSKQ==,type:str]
pricing_service_api_key: ENC[AES256_GCM,data:5CJnkIP7CqefJUHG1Noy4e9Xrevk/hJ7clJszR83TdyaE48SCWjUGQ==,iv:YecAlz1xNzccgAGP4ulEG8tYzLyy5SD2IP9CCZF2MjY=,tag:SQ35pk8+ExAaMMjZv5AFVg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-central-1:823844813531:key/59f4e215-67f4-48bc-9d03-da65870b80e7
          role: arn:aws:iam::823844813531:role/K24.AccessSopsKMS
          created_at: "2022-05-17T06:24:58Z"
          enc: AQICAHhlE+W1VDoEfCyLFJNKxgsoTZvknpSGWiMaH4zFK6yb+AGh42iimP034euei11U4B6mAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMNPzzEbXs8tGHhyCIAgEQgDsXvoooFNGp0yV03ROKA0U+UjFRZKZfesvQA/Dn8QPR7MmclRtfqgszU9kd1s0Z3hyll03VmyVWwmDn7g==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-06-08T10:49:29Z"
    mac: ENC[AES256_GCM,data:VvPN2+jOZwmnSErrK3EgPVqXE/llKCzkT0ZtPBYyrTLrSl+XwSnC41cvTITdi2En6X87mB6vh+WPpt9J0OS5TRMiq78FBdN79QYubdNgPaByD1XqCV3EojyhUsSj2NokrXc+cL8rGfLrRbRioEAyOReuzssO71+Umtf+uyHcw3E=,iv:JK6LeCdzA79+0jPQTX7ylGVA13gUag1XFgAYD33aj2A=,tag:0/9OVc+J9N30EO1ugorH/w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
