pdh_client_id: ENC[AES256_GCM,data:hOsKkLaU/rvp2aYHf8FRwypqG44vnUSm5ks=,iv:/UqtYFUB6mZ2MPoXVlR6vvhNf5xVIp38PF837h8nKEQ=,tag:QNMPV+VDxCdC/CNLjpwlnw==,type:str]
pdh_client_secret: ENC[AES256_GCM,data:YXh81GM8FyUceX7q9CGVO0xGhSdys4/3U4Lws1L5GWbjez041hYgEiltvTsTw7iRCakl,iv:Tr2RQV5KRqI/xmPGM1qzdHIJHUlWQgHAgOlI3cTArSs=,tag:81gysUNd6apV4dcI5YN1AA==,type:str]
pricing_service_api_key: ENC[AES256_GCM,data:d4gwWd1LTsM7/77iPlE0N0NP2tkTZDGoOQoPqQ3y3GAMqVi1aKxU,iv:6RERBaP1GiZ+ppmsve/AJlA7Rv52KM1f8hCv3ZyYp8E=,tag:DMKHXHaI9fg891PXDmOOsg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-central-1:823844813531:key/59f4e215-67f4-48bc-9d03-da65870b80e7
          role: arn:aws:iam::823844813531:role/K24.AccessSopsKMS
          created_at: "2022-05-17T06:37:17Z"
          enc: AQICAHhlE+W1VDoEfCyLFJNKxgsoTZvknpSGWiMaH4zFK6yb+AFkhHKz1BG0km00oVdVgg06AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMcDLktx1Z8sf7c5+hAgEQgDvZ5Od1c8lx3MIop8MaT4cUm3FeuYPG1mpkgLqwMCMX5Yc0BLTlQGIca3+7PoO77lBoj9QTSTkRnS/AkQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-06-08T10:50:00Z"
    mac: ENC[AES256_GCM,data:XKjthRiPkMIuXLDNuYS7yA88xbLiVpd5zDkDkwGGcRSFFJbWfbatH6yel2c9JawWEzeIFKrQzTQEVSZgihxIjjheMivndOtHBdS1VOmW8u2tv7k4SKGV4tGqrkJaauBGoBt4ToNMmm+LKBDYMZTLjWbZZ5HTzFoX5R4t9RFAqyw=,iv:2y70i83ZZYJw3tIe/vGfsYTb6g/rR9J8OxoOgiGrOAA=,tag:Fyds++NsgYO8ZvzRzoubRw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
