terraform_role_arn         = "arn:aws:iam::556221214774:role/K24.Terraform"
source_repo_branch         = "master"
db_instance_class          = "db.t3.medium"
domain_name                = "prod.kfzteile24.io"
environment                = "prod"
stage                      = "production"
ecp_new_order_sns          = "arn:aws:sns:eu-central-1:726569450381:development-order-export"