package de.kfzteile24.salesOrderHub.constants;

public enum BPMEventEnum {
    EVENT_THROW_MSG_ORDER_PAYMENT_SECURED(EventNames.EVENT_THROW_MSG_ORDER_PAYMENT_SECURED),
    EVENT_THROW_MSG_ORDER_CREATED(EventNames.EVENT_THROW_MSG_ORDER_CREATED),
    EVENT_START_SUB_PROCESS_ORDER_ITEM(EventNames.EVENT_START_SUB_PROCESS_ORDER_ITEM),
    EVENT_END_ORDER_ITEM_FINISHED(EventNames.EVENT_END_ORDER_ITEM_FINISHED),
    EVENT_CATCH_MSG_ORDER_ITEM_TRANSMITTED_TO_LOGISTICS(EventNames.EVENT_CATCH_MSG_ORDER_ITEM_TRANSMITTED_TO_LOGISTICS),
    EVENT_CATCH_MSG_ORDER_ITEM_TRACKING_ID_RECEIVED(EventNames.EVENT_CATCH_MSG_ORDER_ITEM_TRACKING_ID_RECEIVED),
    EVENT_CATCH_MSG_ORDER_ITEM_ITEM_DELIVERED(EventNames.EVENT_CATCH_MSG_ORDER_ITEM_ITEM_DELIVERED),
    EVENT_CATCH_MSG_ORDER_ITEM_PACKING_STARTED(EventNames.EVENT_CATCH_MSG_ORDER_ITEM_PACKING_STARTED),
    EVENT_END_ORDER_ITEM_CANCELLATION_FULLFILMENT_NOT_HANDLED(EventNames.EVENT_END_ORDER_ITEM_CANCELLATION_FULLFILMENT_NOT_HANDLED),
    EVENT_START_MSG_ORDER_ITEM_CANCELLATION_RECEIVED(EventNames.EVENT_START_MSG_ORDER_ITEM_CANCELLATION_RECEIVED),
    EVENT_THROW_MSG_ORDER_ITEM_FULLFILMENT_CANCELLED(EventNames.EVENT_THROW_MSG_ORDER_ITEM_FULLFILMENT_CANCELLED),
    EVENT_END_ORDER_ITEM_CANCELLATION_FULLFILMENT_HANDLED(EventNames.EVENT_END_ORDER_ITEM_CANCELLATION_FULLFILMENT_HANDLED),
    EVENT_CATCH_MSG_ORDER_ITEM_TOUR_STARTED(EventNames.EVENT_CATCH_MSG_ORDER_ITEM_TOUR_STARTED),
    EVENT_CATCH_MSG_ORDER_ITEM_PREPARED_FOR_PICKUP(EventNames.EVENT_CATCH_MSG_ORDER_ITEM_PREPARED_FOR_PICKUP),
    EVENT_CATCH_MSG_ORDER_ITEM_PICKED_UP(EventNames.EVENT_CATCH_MSG_ORDER_ITEM_PICKED_UP),
    EVENT_START_MSG_ORDER_ITEM_DROPSHIPMENT_CANCELLATION_RECEIVED(EventNames.EVENT_START_MSG_ORDER_ITEM_DROPSHIPMENT_CANCELLATION_RECEIVED),
    EVENT_END_ORDER_ITEM_CANCELLATION_DROPSHIPMENT_NOT_HANDLED(EventNames.EVENT_END_ORDER_ITEM_CANCELLATION_DROPSHIPMENT_NOT_HANDLED),
    EVENT_THROW_ORDER_ITEM_CANCELLATION_DROPSHIPMENT_HANDLED(EventNames.EVENT_THROW_ORDER_ITEM_CANCELLATION_DROPSHIPMENT_HANDLED),
    EVENT_THROW_MSG_ORDER_ITEM_DROPSHIPMENT_CANCELLED(EventNames.EVENT_THROW_MSG_ORDER_ITEM_DROPSHIPMENT_CANCELLED),
    EVENT_START_MSG_ORDER_ITEM_DELIVERY_ADDRESS_CHANGE(EventNames.EVENT_START_MSG_ORDER_ITEM_DELIVERY_ADDRESS_CHANGE),
    EVENT_END_ORDER_ITEM_DELIVERY_ADDRESS_NOT_CHANGED(EventNames.EVENT_END_ORDER_ITEM_DELIVERY_ADDRESS_NOT_CHANGED),
    EVENT_THROW_MSG_DELIVERY_ADDRESS_CHANGED(EventNames.EVENT_THROW_MSG_DELIVERY_ADDRESS_CHANGED),
    EVENT_CATCH_ESCALATION_ORDER_ITEM_ORDER_CANCELLED(EventNames.EVENT_CATCH_ESCALATION_ORDER_ITEM_ORDER_CANCELLED),
    EVENT_THROW_MSG_ORDER_ITEM_CANCELLED(EventNames.EVENT_THROW_MSG_ORDER_ITEM_CANCELLED),
    EVENT_START_MSG_INVOICE_ADDRESS_CHANGE_RECEIVED(EventNames.EVENT_START_MSG_INVOICE_ADDRESS_CHANGE_RECEIVED),
    EVENT_INVOICE_ADDRESS_NOT_CHANGED(EventNames.EVENT_INVOICE_ADDRESS_NOT_CHANGED),
    EVENT_INVOICE_ADDRESS_CHANGED(EventNames.EVENT_INVOICE_ADDRESS_CHANGED),
    EVENT_START_MSG_INVOICE_CREATED(EventNames.EVENT_START_MSG_INVOICE_CREATED),
    EVENT_INVOICE_SAVED(EventNames.EVENT_INVOICE_SAVED),
    EVENT_THROW_MSG_ORDER_COMPLETED(EventNames.EVENT_THROW_MSG_ORDER_COMPLETED),
    EVENT_START_MSG_ORDER_RECEIVED_FROM_MARKETPLACE(EventNames.EVENT_START_MSG_ORDER_RECEIVED_FROM_MARKETPLACE),
    EVENT_START_MSG_ORDER_RECEIVED_FROM_E_C_P(EventNames.EVENT_START_MSG_ORDER_RECEIVED_FROM_E_C_P),
    EVENT_START_MSG_ORDER_RECEIVED_FROM_CUSTOMER_CARE(EventNames.EVENT_START_MSG_ORDER_RECEIVED_FROM_CUSTOMER_CARE),
    EVENT_START_MSG_ORDER_RECEIVED_FROM_BRANCH(EventNames.EVENT_START_MSG_ORDER_RECEIVED_FROM_BRANCH),
    EVENT_START_MSG_ORDER_RECEIVED_FROM_GARAGE(EventNames.EVENT_START_MSG_ORDER_RECEIVED_FROM_GARAGE),
    EVENT_THROW_MSG_ORDER_VALIDATED(EventNames.EVENT_THROW_MSG_ORDER_VALIDATED),
    EVENT_END_MSG_ORDER_NOT_VALID_COMPLETED(EventNames.EVENT_END_MSG_ORDER_NOT_VALID_COMPLETED);
    private final String eventName;

    BPMEventEnum(final String eventName) {
        this.eventName = eventName;
    }

    String getEventName() {
        return eventName;
    }
}
