version: '3.4'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack-full
    network_mode: bridge
    ports:
      - "4566:4566"
      - "${PORT_WEB_UI-8081}:8080"
    environment:
      - SERVICES=sns,sqs
      - DEFAULT_REGION=eu-central-1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME_EXTERNAL=${HOSTNAME_EXTERNAL- }
    volumes:
      - "vol_tmp:/tmp/localstack"
      - "vol_data:/tmp/localstack/data"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  vol_tmp:
  vol_data:
