name: Run unit tests & codacy coverage

env:
  MAVEN_SETTINGS_FILE: '.github/scripts/.m2/settings.xml'
  GPR_READONLY_USER: ${{secrets.GPR_READONLY_USER}}
  GPR_READONLY_TOKEN: ${{secrets.GPR_READONLY_TOKEN}}
  CODACY_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
  FLYWAY_URL: 'jdbc:postgresql://localhost:5432/soh'
  FLYWAY_USER: 'soh'
  FLYWAY_PASSWORD: 'soh'
  POSTGRES_DB: 'soh'
  POSTGRES_USER: 'soh'
  POSTGRES_PASSWORD: 'soh'
  AWS_HOST: localstack
  SERVICES: sns,sqs # Add more services depending on your test case
  soh_order_created: 'arn:aws:sns:eu-central-1:000000000000:soh-order-created'
  soh_order_created_v2: 'arn:aws:sns:eu-central-1:000000000000:soh-order-created-v2'
  soh_order_completed: 'arn:aws:sns:eu-central-1:000000000000:soh-order-completed'
  soh_order_cancelled: 'arn:aws:sns:eu-central-1:000000000000:soh-order-cancelled'
  soh_order_item_cancelled: 'arn:aws:sns:eu-central-1:000000000000:soh-order-item-cancelled'
  soh_order_rows_cancelled: 'arn:aws:sns:eu-central-1:000000000000:soh-order-rows-cancelled-v1'
  soh_invoice_address_changed: 'arn:aws:sns:eu-central-1:000000000000:soh-invoice-address-changed'
  soh_delivery_address_changed: 'arn:aws:sns:eu-central-1:000000000000:soh-delivery-address-changed'
  soh_sqs_ecp_shop_orders: 'http://localhost:4566/000000000000/soh-ecp-shop-orders-queue'
  soh_sqs_order_item_shipped: 'http://localhost:4566/000000000000/soh-order-item-shipped-queue'
  soh_sqs_order_payment_secured: 'http://localhost:4566/000000000000/soh-order-payment-secured-queue'
  soh_sqs_order_item_transmitted_to_logistic: 'http://localhost:4566/000000000000/soh-order-item-transmitted-to-logistic-queue'
  soh_sqs_order_item_packing_started: 'http://localhost:4566/000000000000/soh-order-item-packing-started-queue'
  soh_sqs_order_item_tracking_id_received: 'http://localhost:4566/000000000000/soh-order-item-tracking-id-received-queue'
  soh_sqs_order_item_tour_started: 'http://localhost:4566/000000000000/soh-order-item-tour-started-queue'
  soh_sqs_invoices_from_core: 'http://localhost:4566/000000000000/soh-invoices-from-core-queue'

on: [push, pull_request]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-unit-test-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-unit-test-
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run unit test
        run:
          mvn -s ${MAVEN_SETTINGS_FILE} clean test -U -Dspring.profiles.active=test
      - name: Create coverage report files
        run:
          mvn jacoco:report
      - name: Upload code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-file
          path: target/site/jacoco/jacoco.xml

  codacy-coverage-reporter:
    needs: [ unit-test, integration-test ]
    runs-on: ubuntu-latest
    name: Codacy code coverage upload
    steps:
      - uses: actions/checkout@master
      - name: Download code coverage report
        uses: actions/download-artifact@v2
        with:
          name: code-coverage-file
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ env.CODACY_TOKEN }}
          coverage-reports: jacoco.xml

  integration-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          PGDATA: /postgres/db
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
      localstack:
        image: localstack/localstack-full
        ports:
          - "4566:4566"
        env:
          SERVICES: sns,sqs
          DEFAULT_REGION: eu-central-1
          DOCKER_HOST: unix:///var/run/docker.sock
          HOST_TMP_FOLDER: "/tmp"
          HOSTNAME_EXTERNAL: ${{ env.AWS_HOST }}
        options: >-
          --name localstack
          --health-cmd "curl -sS 127.0.0.1:4566 || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-int-test-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-int-test-
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Set up sns topics & sqs
        run:
          bash ./.github/scripts/prepare_sns_sqs.sh
      - name: Run integration test
        run: |
          mvn -s ${MAVEN_SETTINGS_FILE} flyway:migrate
          mvn -s ${MAVEN_SETTINGS_FILE} clean verify -Pintegration -e -Dspring.profiles.active=test